/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#005049',
        'on-secondary': '#ffffff',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#b6c4ff',
        'primary-fixed': '#dce1ff',
        'on-primary-container': '#90a8ff',
        'on-secondary-fixed': '#00201d',
        'on-background': '#191c1e',
        'on-surface-variant': '#444651',
        'inverse-on-surface': '#eff1f3',
        'on-error': '#ffffff',
        'tertiary-container': '#6e2c00',
        background: '#f7f9fb',
        secondary: '#006a61',
        'on-tertiary-fixed-variant': '#773205',
        'on-tertiary-container': '#f39461',
        outline: '#757682',
        'surface-tint': '#4059aa',
        'on-tertiary-fixed': '#341100',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary-fixed': '#ffdbcb',
        'on-secondary-container': '#006f66',
        'on-surface': '#191c1e',
        'secondary-fixed': '#89f5e7',
        'secondary-container': '#86f2e4',
        'on-tertiary': '#ffffff',
        surface: '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'surface-bright': '#f7f9fb',
        'primary-container': '#1e3a8a',
        primary: '#00236f',
        tertiary: '#4b1c00',
        'outline-variant': '#c5c5d3',
        'on-primary-fixed-variant': '#264191',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00164e',
        'tertiary-fixed-dim': '#ffb691',
        'on-primary': '#ffffff',
        'inverse-primary': '#b6c4ff',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        '2xl': '48px',
        base: '8px',
        '3xl': '64px',
        md: '16px',
        xs: '4px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
