// No-backend data layer.
//
// Replaces the old fetch-against-localhost:8000 client with a loader that
// pulls the pre-built static datasets (public/data/*.json, generated by
// scripts/build-data.mjs) and caches them in memory. The typed API functions
// in ./index.ts compute everything else locally.

import type { ApiCollege, Meta } from './types';

const TOKEN_KEY = 'ck_token';
export const getToken = (): string | null => localStorage.getItem(TOKEN_KEY);
export const setToken = (t: string) => localStorage.setItem(TOKEN_KEY, t);
export const clearToken = () => localStorage.removeItem(TOKEN_KEY);

// Static data lives under the site's base URL so it works on any Vercel domain.
const DATA_BASE = `${import.meta.env.BASE_URL}data`;

let _metaPromise: Promise<Meta> | null = null;
let _collegesPromise: Promise<ApiCollege[]> | null = null;

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url} (${res.status})`);
  return res.json() as Promise<T>;
}

export function loadMeta(): Promise<Meta> {
  if (!_metaPromise) _metaPromise = fetchJson<Meta>(`${DATA_BASE}/meta.json`);
  return _metaPromise;
}

export function loadColleges(): Promise<ApiCollege[]> {
  if (!_collegesPromise) _collegesPromise = fetchJson<ApiCollege[]>(`${DATA_BASE}/colleges.json`);
  return _collegesPromise;
}

// ── Groq (optional, browser-side) ──────────────────────────────────────────
// Used by the AI Counselor and the comparison summary. The key is read from a
// build-time env var (set VITE_GROQ_API_KEY in Vercel). If it's absent or the
// call fails, callers fall back to deterministic templates.
const GROQ_API_KEY = (import.meta.env.VITE_GROQ_API_KEY as string | undefined) ?? '';
const GROQ_MODEL = (import.meta.env.VITE_GROQ_MODEL as string | undefined) ?? 'llama-3.3-70b-versatile';

export const groqAvailable = (): boolean => Boolean(GROQ_API_KEY);

export async function groqChat(
  system: string,
  messages: { role: 'user' | 'assistant'; content: string }[],
  opts: { temperature?: number; maxTokens?: number } = {}
): Promise<string> {
  if (!GROQ_API_KEY) throw new Error('No Groq API key configured');
  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${GROQ_API_KEY}`,
    },
    body: JSON.stringify({
      model: GROQ_MODEL,
      messages: [{ role: 'system', content: system }, ...messages],
      temperature: opts.temperature ?? 0.3,
      max_tokens: opts.maxTokens ?? 900,
    }),
  });
  if (!res.ok) throw new Error(`Groq error ${res.status}`);
  const data = await res.json();
  return (data?.choices?.[0]?.message?.content ?? '').trim();
}
